project:
  type: book
  output-dir: .

filters:
  - acronyms
acronyms:
  fromfile: acronyms.qmd
  loa_title: "Acronyms and abbreviations"
  include_unused: true
  loa_header_classes:
      - unnumbered
      - unlisted

date: today
date-modified: last-modified
date-format: "Do MMMM YYYY"  
bibliography: thesis.bib
csl: harvard-CTR-10-hang.csl
  
book:
  title: "The inside of a ping-pong ball"
  # output-file: My_thesis.pdf
  subtitle: "It's shiny and bright"
  description: |
    Thesis of a postgraduate research project being conducted at the University of Edinburgh under the supervision of [Professor Kermit T. Frog](https://www.ed.ac.uk/profile/kermit) and [Dr. G. O'Nzo](https://www.ed.ac.uk/profile/gonzo). 
  author: 
    name: "I. M. A. Student"
    affiliation: University of Edinburgh
    # orcid: 0000-0000-0000-0000
  date: today

  chapters:
    # -------------------------------------------------------------------
    # title page, abstract, lay summary, declaration, preface, acknowledgements, 
    # table of contents, list of tables, list of figures, abbreviations; 
    # the body of the thesis; references; 
    # and finally appendices.
    # -------------------------------------------------------------------
    - index.qmd # contains the (placeholder) abstract and the _preface.qmd
    # declaration, dedication, acknowledgements in _front-matter.qmd, to be included from index.qmd
    # table of contents (and lists of tables and figures) included in index.qmd
    - 10-introduction.qmd
    - 20-conceptual-framework.qmd
    - 30-method.qmd
    - 40-discussion.qmd
    - 50-conclusion.qmd
    - references.qmd
  # appendices: 
    - 99-appendices.qmd
    
format:
  pdf:
    documentclass: scrbook
    pdf-engine: xelatex
    papersize: a4
    include-in-header: latex/include-in-header.tex
    include-after-body: latex/after-body.tex
    template-partials: 
      - latex/before-body.tex
      - latex/toc.tex
    geometry:
      - inner=2.5cm
      - outer=2.5cm
      - top=2.5cm
      - bottom=2.5cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    toc: true
    toc-depth: 3
    number-depth: 2
    lof: true
    lot: true
    supervisor: 
      - name: Professor Kermit T. Frog
        affiliation: University of Seattle
      - name: Dr. G. O'Nzo
        affiliation: University of Tacoma
    examiner: 
      - name: Professor Fozzie Bear
        affiliation: University of Kerala
      - name: Doctor Piggy
        affiliation: Washington University

    indent: true
    linestretch: 1.5
    fontsize: 12pt

    mainfont: "IBM Plex Serif"
    CJKmainfont: "Source Han Serif"
    sansfont: Optima
    monofont: Menlo
    mathfont: "TeX Gyre Termes Math"
    link-citations: true
